<?php

class GroupTableSeeder extends Seeder {

	public function run()
	{
		DB::table('groups')->delete();

		Sentry::createGroup(array(
			'name' => 'administrador',
			'permissions' => array(
				'admin' => 1,
				'deed_index' => 1,
				'deed_create' => 1,
				'deed_update' => 1,
				'deed_delete' => 1,
				'agrarian_index' => 1,
				'agrarian_create' => 1,
				'agrarian_update' => 1,
				'agrarian_delete' => 1,
				'civil_index' => 1,
				'civil_create' => 1,
				'civil_update' => 1,
				'civil_delete' => 1,
				'penal_index' => 1,
				'penal_create' => 1,
				'penal_update' => 1,
				'penal_delete' => 1,
				'record_index' => 1,
				'record_create' => 1,
				'record_update' => 1,
				'record_delete' => 1,
				'notary_index' => 1,
				'notary_create' => 1,
				'notary_update' => 1,
				'notary_delete' => 1,
				'municipality_index' => 1,
				'municipality_create' => 1,
				'municipality_update' => 1,
				'municipality_delete' => 1,
				'user_index' => 1,
				'user_create' => 1,
				'user_update' => 1,
				'user_delete' => 1,
				'group_index' => 1,
				'group_create' => 1,
				'group_update' => 1,
				'group_delete' => 1,
			)
		));
		Sentry::createGroup(array(
			'name' => 'director',
			'permissions' => array(
				'admin' => 1,
				'deed_index' => 1,
				'deed_create' => 1,
				'deed_update' => 1,
				'deed_delete' => 1,
				'agrarian_index' => 1,
				'agrarian_create' => 1,
				'agrarian_update' => 1,
				'agrarian_delete' => 1,
				'civil_index' => 1,
				'civil_create' => 1,
				'civil_update' => 1,
				'civil_delete' => 1,
				'penal_index' => 1,
				'penal_create' => 1,
				'penal_update' => 1,
				'penal_delete' => 1,
				'record_index' => 1,
				'record_create' => 1,
				'record_update' => 1,
				'record_delete' => 1,
				'notary_index' => 1,
				'notary_create' => 1,
				'notary_update' => 1,
				'notary_delete' => 1,
				'municipality_index' => 1,
				'municipality_create' => 1,
				'municipality_update' => 1,
				'municipality_delete' => 1,
				'user_index' => 1,
				'user_create' => 1,
				'user_update' => 1,
				'user_delete' => 1,
				'group_index' => 1,
				'group_create' => 1,
				'group_update' => 1,
				'group_delete' => 1,
			)
		));
		Sentry::createGroup(array(
			'name' => 'secretaria',
			'permissions' => array(
				'admin' => 1,
				'deed_index' => 1,
				'deed_create' => 1,
				'deed_update' => 1,
				'deed_delete' => 1,
				'agrarian_index' => 1,
				'agrarian_create' => 1,
				'agrarian_update' => 1,
				'agrarian_delete' => 1,
				'civil_index' => 1,
				'civil_create' => 1,
				'civil_update' => 1,
				'civil_delete' => 1,
				'penal_index' => 1,
				'penal_create' => 1,
				'penal_update' => 1,
				'penal_delete' => 1,
				'record_index' => 1,
				'record_create' => 1,
				'record_update' => 1,
				'record_delete' => 1,
				'notary_index' => 1,
				'notary_create' => 1,
				'notary_update' => 1,
				'notary_delete' => 1,
				'municipality_index' => 1,
				'municipality_create' => 1,
				'municipality_update' => 1,
				'municipality_delete' => 1,
				'user_index' => 1,
				'user_create' => 1,
				'user_update' => 1,
				'user_delete' => 1,
				'group_index' => 1,
				'group_create' => 1,
				'group_update' => 1,
				'group_delete' => 1,
			)
		));
		Sentry::createGroup(array(
			'name' => 'practicante',
			'permissions' => array(
				'admin' => 1,
				'deed_index' => 1,
				'deed_create' => 1,
				'deed_update' => 1,
				'deed_delete' => 1,
				'agrarian_index' => 1,
				'agrarian_create' => 1,
				'agrarian_update' => 1,
				'agrarian_delete' => 1,
				'civil_index' => 1,
				'civil_create' => 1,
				'civil_update' => 1,
				'civil_delete' => 1,
				'penal_index' => 1,
				'penal_create' => 1,
				'penal_update' => 1,
				'penal_delete' => 1,
				'record_index' => 1,
				'record_create' => 1,
				'record_update' => 1,
				'record_delete' => 1,
				'notary_index' => 1,
				'notary_create' => 1,
				'notary_update' => 1,
				'notary_delete' => 1,
				'municipality_index' => 1,
				'municipality_create' => 1,
				'municipality_update' => 1,
				'municipality_delete' => 1,
			)
		));
		Sentry::createGroup(array(
			'name' => 'usuario',
			'permissions' => array(
				'user' => 1,
			)
		));
	}
}